# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32ee568b36b12dbbd3c34824ae08f33cdea2b07b9edf37a227431ead8c8c608707a6bf52caf398196a8f2f9c540c7ea89216d332f8858fc067d19afec176455a

test:
  secret_key_base: 5cfd8b6ec4d960e67199e9afa9d6d11cb8d80b040b46e18d064c151838963b3ba96709d82a7d18516a7c0b4c86baf1e1917d36eeef8b0465c88acdafdc59ed52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
